default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list-2_development

test:
  <<: *default
  database: rails-watch-list-2_test
